### ISSUE TITLE
Error- Executing the export-surround-to-git - 

### ISSUE THREAD

**Issue by rohinigajawada** [JElchison/export-surround-to-git#46]
Hi,

Your help is highly appreciated.
Downloaded the this package and now I am trying to execute the script
I am new to surround SCM ,however when I execute the below command I get this error
Executed in git bash as below:
python C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py "beacon" "C:/SurroundSCM/class a/reset app" 

Kindly please help me in fixing this.

~Roh

**Comment by JElchison** [comment]
Hi @rohinigajawada, you didn't include the error that you're receiving.  However, you're also not following the usage published on the [README](https://github.com/JElchison/export-surround-to-git/blob/develop/README.md).  If you adhere to the usage, you will have better luck.

Take note:  As noted on the [README](https://github.com/JElchison/export-surround-to-git/blob/develop/README.md), this project is currently abandoned.  You're welcome to try to build upon it if you like, but I'm not able to provide support anymore.

Good luck!

**Comment by rohinigajawada** [comment]
I am new to SurroundSCM tool, so not sure how to parse the values, trying different ways.

However can you please guide me please to. 
Migrating from surround scm to Git is very much needed to me right now.

Thanks in advance,

**Comment by rohinigajawada** [comment]
Below is my error msg and command i executed:

C:\Program Files (x86)\Seapine\Surround SCM\SSCM_Repo>python C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.p
y -m "BnR accounting reports" -p "BnR accounting reports/+code+"
[+] Beginning parse phase...
Traceback (most recent call last):
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 643, in <module>
    main()
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 638, in main
    handle_command(parser)
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 613, in handle_command
    cmd_parse(args.mainline[0], args.path[0], database)
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 334, in cmd_parse
    branches = find_all_branches_in_mainline_containing_path(mainline, path)
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 172, in find_all_branches_in_mainline_contai
ning_path
    return get_lines_from_sscm_cmd(cmd)
  File "C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py", line 161, in get_lines_from_sscm_cmd
    sys.stderr.write(stderrdata)
TypeError: write() argument must be str, not bytes

**Comment by JElchison** [comment]
Hi @rohinigajawada.

By way of reminder:  As noted on the [README](https://github.com/JElchison/export-surround-to-git/blob/develop/README.md), this project is currently abandoned.  You're welcome to try to build upon it if you like, but I'm not able to provide support anymore.

As a one-time courtesy, however, I'll look at your error message.

You didn't provide much context, but according to your stack trace, you're crashing on line 161, which is printing output from your Surround client.  It looks like the version of Surround you're using is returning non-ASCII characters for some command.

By way of reminder, if you didn't see it on the README, this project was last tested using the following environment:

```
   * Python 2.7.6
   * GNU bash, version 4.3.11(1)-release (i686-pc-linux-gnu)
   * sscm command-line client version:  2013.0.0 Build 23 (Linux)
   * Git version 1.9.1
   * Ubuntu 14.04.1 LTS
   * Linux 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:01 UTC 2014 i686 i686 i686 GNU/Linux
```

If you're using any environment other than what's listed above, the script may not work.  It's also possible that you're using Python3 instead of Python2.

Sadly, I'm not able to spend any more time helping you.  However, feel free to report back below with any updates, if you'd like to assist others in the future who run into your same problem.

Good luck!

**Comment by rohinigajawada** [comment]
Need your help, Sorry to trouble you by posting my errors

[+] Beginning parse phase...
'sed' is not recognized as an internal or external command,
operable program or batch file.
[+] Parse phase complete
[+] Beginning export phase...

**Comment by rohinigajawada** [comment]
previous error on cmd.exe windows
now this error on gitbash
rohini.gajawada@NAP-LT170605ZW7 MINGW64 /c/export-surround-to-git-develop/my-new-repo (master)
$ python C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py -m "BnR accounting reports" -p "BnR accounting reports/code/" | git fast-import --stats --export-marks=marks.txt
[+] Beginning parse phase...
'mainline' is not recognized as an internal or external command,
operable program or batch file.
[+] Parse phase complete
[+] Beginning export phase...

**Comment by rohinigajawada** [comment]
now I get this error:
[+] Beginning parse phase...
fatal: Unsupported command: lsbranch error: The entered -b option is not supported.
fast-import: dumping crash report to .git/fast_import_crash_160
error: Unable to write marks file marks.txt | find -r 's/ \((baseline|snapshot)\)$//g': Invalid argument
[+] Parse phase complete
[+] Beginning export phase...

**Comment by rohinigajawada** [comment]
rohini.gajawada@NAP-LT170605ZW7 MINGW64 /c/export-surround-to-git-develop/my-new-repo (master)
$ python C:/export-surround-to-git-develop/export-surround-to-git-develop/export-surround-to-git.py -m '[rpt] BnR accounting reports' -p '[rpt] BnR accounting reports/+ code +'
[+] Beginning parse phase...
The system cannot find the path specified.
[+] Parse phase complete
[+] Beginning export phase...

[+] Export complete.  Your new Git repository is ready to use.
Don't forget to run `git repack` at some future time to improve data locality and access performance.
