### ISSUE TITLE
Usage of script 

### ISSUE THREAD

**Issue by rohinigajawada** [JElchison/export-surround-to-git#48]
export-surround-to-git.py [-h] [-m MAINLINE] [-p PATH] [-d DATABASE]
                                 [--version]
                                 [command]

I am new to surround SCM, can you please let me know what is -d <DATABASE> while connecting i just give servername and port and my credentials then from where i can get DB ?

**Comment by JElchison** [comment]
Hi @rohinigajawada.  As I've iterated to you several times, I am no longer maintaining this project.  This project is broken and cannot be successful unless Seapine updates their API.  Please see the README for answers to your usage questions.
